name: Compile files into downloadable formats
on: [push]
jobs:
  compile_files:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y-%m-%d_%H-%M")"
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create complete data JSON
      run: |
        python3 -c "from glob import glob; from json import dump as jdump; data = {game.split('/')[-1].strip() : {txt.split('/')[-1].strip().split('.txt')[0]:open(txt).read().strip()} for txt in glob('%s/*.txt' % game)} for game in glob('games/*')}; f = open('data.json','w'); dump(data,f); f.close()"
    - name: Upload complete data JSON to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data.json
        asset_name: PSX.data.json
        tag: ${{ github.ref }}
        overwrite: true
