name: Compile files into downloadable formats
on: [push]
jobs:
  compile_files:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y-%m-%d_%H-%M")"
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run data building scripts
      run: |
        wget https://github.com/niemasd/GameDB/raw/main/scripts/create_complete_data_json.py && python3 create_complete_data_json.py
    - name: Upload complete data JSON to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: data.json
        asset_name: PSX.data.json
        tag: ${{ steps.tag.outputs.release_tag }}
        overwrite: true
